### ISSUE TITLE
failed to unzip quilt_instruct.zip

### ISSUE THREAD

**Issue by lsnls** [aldraus/quilt-llava#6]
Hello! 
I failed while unzipping the `quilt_instruct.zip` on linux. When I use `unzip quilt_instruct.zip`, an error is reported as shown in Figure 1.When I use `jar xvf quilt_instruct.zip`, an error is reported as shown in Figure 2. 
Looking forward to your reply, thanks!

Figure1:
![QBYV9$80J}@X1T3N~}QFA9A](https://github.com/aldraus/quilt-llava/assets/154673615/ea15fbea-4144-45bc-a202-f7ded904493b)

Figure2:
![61T`1KCEA~$I@YG`FWA1VGY](https://github.com/aldraus/quilt-llava/assets/154673615/6e6dc987-aa52-410c-86c2-ad1f08918a45)

**Comment by wisdomikezogwo** [comment]
Hmm, I will try to replicate this now on a new env and with the exact download you have and get back to you.

**Comment by wisdomikezogwo** [comment]
Just unzipped a fresh download of the zip file and it went without a hitch.
please try to use `unzip -n quilt_instruct.zip` on a complete download with `ls -lh` showing 26G.

If this issue persists, let me know I can find other ways to get you the dataset.
Apologies for the late reply as well.

**Comment by lsnls** [comment]
Hello! Thank you for your reply!

I re-downloaded the complete `quilt_instruct.zip` file, this time I didn't encounter an error. But the folder size after I unzipped it is `16G`, which doesn't match your 26G, which makes me confused.

**Comment by wisdomikezogwo** [comment]
This happens when zipping already well compressed file types like .png, so here the single .zip files serves as a bundler much like a folder would do but its also aids faster download speeds as its a single bundle. [see](https://iboysoft.com/questions/compressed-files-on-mac-are-larger-than-the-original.html#:~:text=In%20fact%2C%20zipping%20PNG%20files,and%20overhead%20takes%20up%20space.)
